services:
  - type: web
    name: portfolio-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings

